name: Sync Fork

on:
  schedule:
    - cron: '0 * * * *'  # 每小时同步一次

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Sync Fork
        run: |
          git remote add upstream https://github.com/ORIGINAL_OWNER/ORIGINAL_REPOSITORY.git
          git fetch upstream
          git checkout main
          git merge upstream/main
          git push origin main
