name: TGForwarder # 工作流程的名称
 
on: # 什么时候触发
  schedule:
    - cron: '30 * * * *'  # 定时触发
  push:
    paths-ignore:
      - '**' # 忽略文件变更, **忽略所有
  workflow_dispatch: # 允许手动触发工作流程

 
jobs: # 执行的工作
  run_demo_actions:
    runs-on: ubuntu-22.04 # 在最新版本的 Ubuntu 操作系统环境下运行
    steps: # 要执行的步骤
      - name: Checkout code
        uses: actions/checkout@v4  # 用于将github代码仓库的代码拷贝到工作目录中
        with:
          # 转到 Settings > Secrets and variables > Actions
          # 点击 New repository secret，添加 Secret，名称为 BOT，输入你的token
          token: ${{ secrets.BOT }}
 
      - name: Set up Python
        uses: actions/setup-python@v2 # 用于设置 Python 环境，它允许你指定要在工作环境中使用的 Python 版本
        with:
          python-version: '3.10.10'  # 选择要用的Python版本

      - name: Install requirements.txt
        run: | # 安装依赖包
          pip install -r ./requirements.txt 
 
      - name: Run TGForwarder.py
        env:
          tgsession: ${{ secrets.tgsession }}
        run: python TGForwarder2.py # 执行py文件

      - name: Commit and push history.json file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add history.json
          git commit -m "Update history.json file" || echo "No changes to commit"
          git push https://${{ secrets.BOT }}:x-oauth-basic@github.com/chindden/TGForwarder.git
